### ISSUE TITLE
Unknown widget 'mendix.dropdowncontainer.DropdownContainer'.

### ISSUE THREAD

**Issue by danlawfordMX** [JelteMX/mendix-dropdown-container#1]
When we place the widget within a table we get the following error Unknown widget 'mendix.dropdowncontainer.DropdownContainer'. When we place it outside the table the widget works as expected. 
![error1](https://user-images.githubusercontent.com/58691161/71368504-0e1d0780-25a0-11ea-8637-c1523852f1b7.PNG)
![setup1](https://user-images.githubusercontent.com/58691161/71368529-1f661400-25a0-11ea-9d0d-b43867bf5496.PNG)

You can see the issue in this example project 
[MendixSupportApp.zip](https://github.com/JelteMX/mendix-dropdown-container/files/3995775/MendixSupportApp.zip)

**Comment by zoltanverebes** [comment]
Hi,

I experience the same problem.
I tried to use a dataview inside the list view it looks working fine this way.

**Comment by JelteMX** [comment]
@daniellawford @zoltanverebes which Mendix version are you using?

I'll see if I can reproduce it. Might be a bug in the runtime (not the widget). If so, I'll report it

**Comment by danlawfordMX** [comment]
Hi @JelteMX I was using 8.4.1.

**Comment by luisepalacios** [comment]
Hi Everyone, issue also happens on 8.5.1 happening on a custom widget also

**Comment by JelteMX** [comment]
Alright, I did a little bit of investigation. Indeed, there is some weird behavior going on with this. It looks like the table view is currently causing issues with not only this widget, but others as well. This is not specific to the dropdown widget, but the platform.

@daniellawford I am using your test-project to report this issue to R&D, thanks for providing it.

Stay tuned

**Comment by JelteMX** [comment]
As of now, I have filed a ticket and they are investigating, as this is broader than just this widget. I consider it a platform bug, but I'll wait for feedback.

I reproduced the issue in 8.2.2 as well 

For now, I suggest the following:

- Do not use a **table**, only a layout-grid
- If you use a table and you might have a context-object that you are using (for example, in a listview), surround the dropdown with a data-view. This data-view should have the same object (you can easily do this with a Nanoflow datasource, add the object as input object and return that one. Dumb, but effective). This kind of works in my views

This is the dumbest workaround so far, but it works 😝. Quick and dirty 

Nanoflow:

![Screenshot 2020-01-30 13 37 11](https://user-images.githubusercontent.com/14937393/73450849-89739500-4366-11ea-96e0-9b8d6ecbf317.png)

Table:

![Screenshot 2020-01-30 13 42 23](https://user-images.githubusercontent.com/14937393/73450863-90020c80-4366-11ea-9dd0-00ef1105fdb9.png)

(If you don't have a context, you could create one with a non-persistent entity and a dataview)

**Comment by JelteMX** [comment]
Advice: Update to [8.11](https://docs.mendix.com/releasenotes/studio-pro/8.11), it seems that some issues were found with the pluggable widgets regarding this, should be fixed now.
