### ISSUE TITLE
Loading widget code

### ISSUE THREAD

**Issue by ghost** [JelteMX/mendix-dropdown-container#2]
Hi Jelte,

Thanks for this widget. Very useful and I used in a lot of Mendix projects. In a listview, for every item that is in the listview I want a dropdown container to put action buttons in for changing/deleting that specific list item. 

In our project we are facing some performance issues and we noticed that the dropdown container loads all the code when you open the page. 

Could you improve this widget that it loads the code and logic **after** you press the button to open the dropdown menu? Let me know if this is an interesting improvement to an already great widget.

Keep up the good work!

**Comment by JelteMX** [comment]
Released version [1.2.0](https://github.com/JelteMX/mendix-dropdown-container/releases/tag/1.2.0) in the App Store that does this. It will not render the content while closed, when you disable it (it is in the General tab, last option)
