### ISSUE TITLE
Widget Dropdown Container 'dropdownContainer1' cannot contain widgets of type data view

### ISSUE THREAD

**Issue by Narev** [JelteMX/mendix-dropdown-container#3]
It would be nice if you could nest dataviews within your dropdown container in case you want to conditionally show/hide elements based on nested attributes.

Or is this the same limitation as the snippet one?

**Comment by JelteMX** [comment]
Unfortunately this is a limitation in the platform, not the widget. I hope this changes in the future, but I can't help you with this one at the moment

**Comment by bartheijs** [comment]
Is this platform limitation still in place? I have a use case where a listview (with the use of its on click action) inside of the Dropdown Container widget would meet our clients needs. Thanks!

**Comment by JelteMX** [comment]
Upgrade to at least 8.10 / 8.11 and it should be possible to use that in this widget

**Comment by bartheijs** [comment]
Thanks for the quick reply.

I tried in 8.11.1 and 8.14.0 and doesn't seem to work. Or it's me not completely understanding the way to implement the widget.

![image](https://user-images.githubusercontent.com/16450232/95722604-71ce0980-0c74-11eb-959d-f01a85f47bf5.png)

![image](https://user-images.githubusercontent.com/16450232/95722661-827e7f80-0c74-11eb-9efe-deac6df50624.png)

![image](https://user-images.githubusercontent.com/16450232/95723540-8e1e7600-0c75-11eb-8873-f603b2de39f8.png)

**Comment by bartheijs** [comment]
Hi Jelte,

just to manage expectations, do you think you can have a look in the near future?

Am I doing something wrong or is there some work to be done on the widget?

Otherwise I'll use the DropdownDivConverter.

Thanks!

Gr,

Bart

**Comment by JelteMX** [comment]
Hi @bartheijs,

It seems Mendix still doesn't support some of the widget types inside a `widgets` property, as can be read here: https://docs.mendix.com/apidocs-mxsdk/apidocs/property-types-pluggable-widgets#widgets.

So for now you might have to go back to the DropdownDivConverter
