### ISSUE TITLE
Unknown widget 'mendix.dropdowncontainer.DropdownContainer'.

### ISSUE THREAD

**Issue by BartReyserhove** [JelteMX/mendix-dropdown-container#4]
I am using this widget without any problems in production (Mendix 8.9). I now switched to Mendix 8.10 and I get the error Unknown widget 'mendix.dropdowncontainer.DropdownContainer' again. 

Only when using the widget in a table it seems. But I did apply that workaround by putting it in a dataview in the table then, but still no luck.

**Comment by JelteMX** [comment]
I'll do some digging and see what the issue is

**Comment by JelteMX** [comment]
Unfortunately, I am not able to fix this. This is purely a Platform issue, not the widget. There is nothing I can do on my end. This is still related to #1, so I am considering this a duplicate issue. The workaround is not a solution, but you will have to file a ticket with Mendix to get this fixed.

**Comment by JelteMX** [comment]
Advice: Update to [8.11](https://docs.mendix.com/releasenotes/studio-pro/8.11), it seems that some issues were found with the pluggable widgets regarding this, should be fixed now.

**Comment by BartReyserhove** [comment]
Ah interesting, will do! I have an open ticket at Mendix for this, but not so much reaction it seems ;-)

**Comment by BartReyserhove** [comment]
I just tested this with 8.11 and the issue is indeed resolved
